name = "BitcoinPlumbers"
license = "MIT"
licenselink = "https://github.com/thinkmassive/BitcoinPlumbers/blob/master/LICENSE"
description = "Basic theme for BitcoinPlumbers.org"
homepage = "https://bitcoinplumbers.org/"
tags = []
features = []
min_version = "0.73.0"

[author]
  name = "Alexander Miller"
  homepage = "https://thinkmassive.org"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
