baseURL = "https://bitcoinplumbers.org/"
languageCode = "en-us"
title = "Bitcoin Plumbers Guide"
theme = "basic"
pygmentsUseClasses = true

[params]
author = "Alexander Miller"
description = "Code snippets and quick reference guides for Bitcoiners."
